# Permalinks
permalink:        pretty

# Setup
title:            'ATXopendata.rocks'
tagline:          ''
description:      ''
url:              atxopendata.rocks

author:
  name:           ''
  url:            ''

# Custom vars
version:          0.0.0

github:
  repo:           https://cityofaustin.github.io/atxopendata.rocks/
